name: 'riskpulse_dbt'
version: '1.0.0'
config-version: 2

profile: 'riskpulse_dbt'

model-paths:  ["models"]
analysis-paths: ["analyses"]
test-paths:   ["tests"]
seed-paths:   ["seeds"]
macro-paths:  ["macros"]
snapshot-paths: ["snapshots"]
docs-paths:   ["docs"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  riskpulse_dbt:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: view
      +schema: marts
